remote_theme            : mmistakes/minimal-mistakes

#minimal_mistakes_skin   : "dark"

title                   : MTechSolutions
title_separator         : "-"
subtitle                : Bespoke Software Solutions
logo                    : "/assets/images/logo.png"
author:
  name                  : Stephen Mahon
  email                 : stephen@mtechsolutions.ie
description             : Exam notes for my Red Hat certification journey.
url                     : "http://www.mtechsolutions.ie"
repository              : "mahons/redhat-notes"
words_per_minute        : 200

search                  : true
search_full_content     : true

#google_site_verifiction : ""

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-JK6WYLH9WJ"
    anonymize_ip: true # default

defaults:  
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true      
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "home"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


lunr:
  search_within_pages: false

footer:
  links:    
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mahons"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stephenmahon"

comments:
  provider: "disqus"
  disqus:
    shortname: mtechsolutions

collections:
  - RH124
  - RH134

  # Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
 # - jekyll-seo-tag   
 # - jekyll-remote-theme     

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

compress_html:
  clippings: all
  ignore:
    envs: development

# Reading Files
include:
  - .htaccess
  - _pages