title: My Red Hat Certification Journey 
description: Exam notes for my Red Hat certification journey.
url: "http://redhat.mtechsolutions.ie"

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag  

show_excerpts: true

google_analytics: G-JK6WYLH9WJ

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/Mahons" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/stephenmahon" }