# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Red Hat Certification Journey 
author: 
  #name: Mahons
  #email: stephen@mtechsolutions.ie

description: Exam notes for my Red Hat certification journey.

url: "http://redhat.mtechsolutions.ie" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: G-JK6WYLH9WJ

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true

minima:
  skin: dark

social_links:
  - { platform: github,         user_url: "https://github.com/Mahons" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/stephenmahon" }